/*
 * Canonical research record for the Publications page.
 * Update records here once; the publication list, map, theme timeline and
 * collaboration network are derived from this dataset in script.js.
 */
window.RESEARCH_DATA = {
  updated: "4 September 2026",
  scholarProfile: "https://scholar.google.com/citations?user=bg_ePEIAAAAJ&hl=en",
  publications: [
    { id: "santa-cruz-2026", year: 2026, type: "article", title: "Potential failure scenarios in the Santa Cruz range, Argentina: 20 years after a natural dam collapse", authors: "Romina Solorza, Ivanna Penna, Carla Tapia Baldis, Gökhan Aslan, John Dehls, Pierrick Nicolet, Michel Jaboyedoff", venue: "Landslides", url: "https://doi.org/10.1007/s10346-026-02790-1", citations: 0, themes: ["landslides"], aois: ["santa-cruz"] },
    { id: "leo-pargil-2026", year: 2026, type: "article", title: "Kinematic segmentation of a DSGSD on the flank of the exhumed Leo Pargil Dome (northwestern Himalaya) using InSAR", authors: "Gökhan Aslan, Marcello De Michele, Tim Redfield, Reginald Hermanns, John Dehls", venue: "Geomorphology 501, 110248", url: "https://doi.org/10.1016/j.geomorph.2026.110248", citations: 0, themes: ["landslides"], aois: ["leo-pargil"] },
    { id: "sorfjorden-2026", year: 2026, type: "article", title: "Leakage During Hydropower Tunnel Construction: A Possible Trigger Mechanism for the Earthquake Swarm at Sørfjorden, Norway", authors: "Angélique Marck, Lars Ottemöller, Gökhan Aslan, Odleiv Olesen, Stéphane Rondenay", venue: "The Seismic Record", url: "https://doi.org/10.1785/0320250045", citations: 0, themes: ["tectonics"], aois: ["sorfjorden"] },
    { id: "insar-norway-global-2026", year: 2026, type: "proceeding", title: "From InSAR Norway to a Global Ground Motion Service: Operational Monitoring for Disaster Risk Reduction", authors: "John Dehls, Yngvar Larsen, Marie Bredal, Gökhan Aslan, Dag Anders Moldestad", venue: "ISPRS Archives XLIX-B3-2026, 1457–1464", url: "https://doi.org/10.5194/isprs-archives-XLIX-B3-2026-1457-2026", citations: 0, themes: ["services"], aois: ["norway"] },
    { id: "fringe-irima-2026", year: 2026, type: "abstract", title: "Landslide Investigations within the PEPR IRIMA Framework: Case Studies from the French Alps - Toward operational InSAR processing", authors: "Maureen Shinta Devi, Marcello De Michele, Daniel Raucoules, Aya Cheaib, Séverine Bernardie, Gökhan Aslan, Joël Langlois, Marc Peruzzetto", venue: "13th Fringe Workshop", url: "https://hal.science/hal-05585061", citations: 0, themes: ["landslides"], aois: ["french-alps"] },
    { id: "svalbard-preprint-2026", year: 2026, type: "preprint", title: "Brief Communication - InSAR Svalbard Ground Motion Service: Observing Surface Displacements in the High Arctic", authors: "Marie Bredal, Line Rouyet, Lotte Wendt, Heidi Hindberg, Daniel Stødle, Tom Rune Lauknes, Jelte van Oostveen, Yngvar Larsen, Gökhan Aslan, Emma Hauglin, John Dehls, Anja Sundal, Anna Odh, Dag Anders Moldestad", venue: "EGUsphere preprint", url: "https://doi.org/10.5194/egusphere-2026-2189", citations: 0, themes: ["arctic", "services"], aois: ["svalbard"] },
    { id: "svalbard-manual-2026", year: 2026, type: "report", title: "InSAR Svalbard: Product Description and User Manual", authors: "Marie Bredal, Line Rouyet, Lotte Wendt, Heidi Hindberg, Daniel Stødle, Tom Rune Lauknes, Jelte van Oostveen, Yngvar Larsen, Gökhan Aslan, Emma Hauglin, John Dehls, Anja Sundal, Anna Odh, Dag Anders Moldestad", venue: "InSAR Svalbard technical documentation", url: "https://svalbard.insar.no/docs/User-manual-InSAR-Svalbard.pdf", citations: 0, themes: ["arctic", "services"], aois: ["svalbard"] },
    { id: "svalbard-egu-2026", year: 2026, type: "abstract", title: "InSAR Svalbard Ground Motion Service", authors: "Emma Hauglin, Gökhan Aslan, Marie Bredal, Line Rouyet, John Dehls, Tom Rune Lauknes, Lotte Wendt, Daniel Stødle, Heidi Hindberg, Jelte van Oostveen, Yngvar Larsen", venue: "EGU General Assembly", url: "https://doi.org/10.5194/egusphere-egu26-20200", citations: 0, themes: ["arctic", "services"], aois: ["svalbard"] },
    { id: "jan-mayen-egu-2026", year: 2026, type: "abstract", title: "An earthquake-triggered rock avalanche on Jan Mayen Island conditioned by Arctic warming", authors: "Guilherme W. S. de Melo, Reginald Hermanns, Jacob M. Bendle, Ingo Grevemeyer, Simone Cesca, Aderson F. do Nascimento, Lars Ottemöller, Gökhan Aslan, Quentin Brissaud, Volker Oye, Heidrun Kopp", venue: "EGU General Assembly", url: "https://doi.org/10.5194/egusphere-egu26-22884", citations: 1, themes: ["arctic", "landslides", "tectonics"], aois: ["jan-mayen"] },
    { id: "jan-mayen-ngwm-2026", year: 2026, type: "abstract", title: "Environmental impact of the 2025 Mw 6.5 Jan Mayen earthquake: A climate-change conditioned rock slope failure on Jan Mayen Island, Arctic Ocean", authors: "Guilherme W. S. de Melo, Reginald Hermanns, Jacob M. Bendle, Ingo Grevemeyer, Simone Cesca, Aderson F. do Nascimento, Lars Ottemöller, Gökhan Aslan, Quentin Brissaud, Volker Oye, Heidrun Kopp", venue: "7th Nordic Geological Winter Meeting · invited talk", url: "https://oceanrep.geomar.de/id/eprint/63024", citations: 0, themes: ["arctic", "landslides", "tectonics"], aois: ["jan-mayen"] },
    { id: "joshimath-2025", year: 2025, type: "abstract", title: "Vulnerability Assessment of Buildings Exposed to Deep-seated Landslide Activity in the Joshimath town of Chamoli, Uttarakhand, India", authors: "Shobhana Lakhera, Michel Jaboyedoff, Marc-Henri Derron, Dario Peduto, John Dehls, Gökhan Aslan, Gianfranco Nicodemo, Ajanta Goswami", venue: "EGU General Assembly", url: "https://doi.org/10.5194/egusphere-egu25-18213", citations: 0, themes: ["landslides"], aois: ["joshimath"] },
    { id: "jan-mayen-ssa-2025", year: 2025, type: "abstract", title: "Ground Motions, Infrasound Signals, and Seismic Velocity Perturbations: Environmental Impacts of the Rock Avalanche Induced by the 2025 Mw 6.5 Jan Mayen Strike-slip Earthquake", authors: "Guilherme W. S. de Melo, Reginald Hermanns, Jacob M. Bendle, Ingo Grevemeyer, Simone Cesca, Aderson F. do Nascimento, Lars Ottemöller, Gökhan Aslan, Quentin Brissaud, Volker Oye, Heidrun Kopp", venue: "SSA Environmental Seismology Conference · poster", url: "https://oceanrep.geomar.de/id/eprint/62727", citations: 0, themes: ["arctic", "landslides", "tectonics"], aois: ["jan-mayen"] },
    { id: "leo-pargil-egu-2024", year: 2024, type: "abstract", title: "InSAR Insights into the Massive Himalayan Leo Pargil Landslide", authors: "Gökhan Aslan, Marcello De Michele, Tim Redfield, Mikis van-Boeckel, Reginald Hermanns, François Noël, John Dehls", venue: "EGU General Assembly", url: "https://doi.org/10.5194/egusphere-egu24-4011", citations: 0, themes: ["landslides"], aois: ["leo-pargil"] },
    { id: "insar-norway-egu-2024", year: 2024, type: "abstract", title: "InSAR Norway: Advancing Geohazard Understanding through Wide-Area Analysis", authors: "John Dehls, Marie Bredal, Ivanna Penna, Yngvar Larsen, Gökhan Aslan, Jacob M. Bendle, Martina Böhme, Reginald Hermanns, Vanja S. Haugsnes, François Noël", venue: "EGU General Assembly", url: "https://doi.org/10.5194/egusphere-egu24-4400", citations: 1, themes: ["services", "landslides"], aois: ["norway"] },
    { id: "aral-journal-2023", year: 2023, type: "article", title: "Dynamics of a giant slow landslide complex along the coast of the Aral Sea, Central Asia", authors: "Gökhan Aslan, Marcello De Michele, Daniel Raucoules, François Renard, John Dehls, Ivanna Penna, Reginald Hermanns, Ziyadin Çakır", venue: "Turkish Journal of Earth Sciences 32(6), 819–832", url: "https://doi.org/10.55730/1300-0985.1876", citations: 6, themes: ["landslides"], aois: ["aral-sea"] },
    { id: "gangtok-2023", year: 2023, type: "article", title: "Ground Investigations and Detection and Monitoring of Landslides Using SAR Interferometry in Gangtok, Sikkim Himalaya", authors: "Rajinder Bhasin, Gökhan Aslan, John Dehls", venue: "GeoHazards 4(1)", url: "https://doi.org/10.3390/geohazards4010003", citations: 19, themes: ["landslides"], aois: ["gangtok"] },
    { id: "cape-coral-2023", year: 2023, type: "article", title: "Brackish-water desalination plant modulates ground deformation in the city of Cape Coral, Florida", authors: "Gökhan Aslan, Ivanna Penna, Ziyadin Çakır, John Dehls", venue: "Science of Remote Sensing 7, 100077", url: "https://doi.org/10.1016/j.srs.2023.100077", citations: 4, themes: ["subsidence"], aois: ["cape-coral"] },
    { id: "western-turkey-2022", year: 2022, type: "article", title: "Wide-area ground deformation monitoring in geothermal fields in western Turkey", authors: "Gökhan Aslan, Hakkı Aydın, Ziyadin Çakır", venue: "Turkish Journal of Earth Sciences 31(3), 247–259", url: "https://doi.org/10.55730/1300-0985.1771", citations: 11, themes: ["subsidence"], aois: ["western-turkey"] },
    { id: "north-sikkim-2022", year: 2022, type: "abstract", title: "Sentinel-1 InSAR Time-series Monitoring of the Unstable Rock Slopes in North Sikkim, India", authors: "Gökhan Aslan, John Dehls, Reginald Hermanns, Ivanna Penna, Aniruddha Sengupta, Vikram Gupta", venue: "EGU General Assembly", url: "https://doi.org/10.5194/egusphere-egu22-11320", citations: 0, themes: ["landslides"], aois: ["north-sikkim"] },
    { id: "largest-landslide-2021", year: 2021, type: "article", title: "Transient motion of the largest landslide on earth, modulated by hydrological forces", authors: "Gökhan Aslan, Marcello De Michele, Daniel Raucoules, Séverine Bernardie, Ziyadin Çakır", venue: "Scientific Reports 11, 10407", url: "https://doi.org/10.1038/s41598-021-89899-6", citations: 27, themes: ["landslides"], aois: ["kara-bogaz"] },
    { id: "konya-journal-2021", year: 2021, type: "article", title: "Long-term spatiotemporal evolution of land subsidence in Konya metropolitan area (Turkey) based on multisensor SAR data", authors: "Nurdan Şireci, Gökhan Aslan, Ziyadin Çakır", venue: "Turkish Journal of Earth Sciences 30(5), 681–697", url: "https://doi.org/10.3906/yer-2104-22", citations: 17, themes: ["subsidence"], aois: ["konya"] },
    { id: "aral-igarss-2021", year: 2021, type: "proceeding", title: "Dynamics of a Giant Slow Landslide Along the Coast of the Aral Sea (Central Asia)", authors: "Gökhan Aslan, Marcello De Michele, Daniel Raucoules, François Renard, Ziyadin Çakır", venue: "IEEE IGARSS, 8384–8387", url: "https://doi.org/10.1109/IGARSS47720.2021.9554550", citations: 2, themes: ["landslides"], aois: ["aral-sea"] },
    { id: "kara-bogaz-igarss-2021", year: 2021, type: "proceeding", title: "Transient Reactivation of Kara-Bogaz-Gol Coastal Landslide, Modulated by Hydrological Forces Captured Using InSAR (Turkmenistan)", authors: "Gökhan Aslan, Marcello De Michele, Daniel Raucoules, Séverine Bernardie, Ziyadin Çakır", venue: "IEEE IGARSS, 5239–5242", url: "https://doi.org/10.1109/IGARSS47720.2021.9554182", citations: 0, themes: ["landslides"], aois: ["kara-bogaz"] },
    { id: "french-alps-2020", year: 2020, type: "article", title: "Landslide Mapping and Monitoring Using Persistent Scatterer Interferometry (PSI) Technique in the French Alps", authors: "Gökhan Aslan, Michael Foumelis, Daniel Raucoules, Marcello De Michele, Séverine Bernardie, Ziyadin Çakır", venue: "Remote Sensing 12(8), 1305", url: "https://doi.org/10.3390/rs12081305", citations: 184, themes: ["landslides"], aois: ["french-alps"] },
    { id: "phd-thesis-2019", year: 2019, type: "thesis", title: "Monitoring of Surface Deformation in Northwest Turkey from High-Resolution InSAR: Focus on Tectonic Aseismic Slip and Subsidence", authors: "Gökhan Aslan", venue: "Doctoral thesis · Université Grenoble Alpes / Istanbul Technical University", url: "https://acikbilim.yok.gov.tr/handle/20.500.12812/127221", citations: 13, themes: ["tectonics", "subsidence"], aois: ["northwest-turkey"] },
    { id: "izmit-jgr-2019", year: 2019, type: "article", title: "Shallow Creep Along the 1999 Izmit Earthquake Rupture (Turkey) From GPS and High Temporal Resolution Interferometric Synthetic Aperture Radar Data (2011–2017)", authors: "Gökhan Aslan, Cécile Lasserre, Ziyadin Çakır, Semih Ergintav, Seda Özarpacı, Uğur Doğan, Roger Bilham, François Renard", venue: "Journal of Geophysical Research: Solid Earth 124", url: "https://doi.org/10.1029/2018JB017022", citations: 74, themes: ["tectonics"], aois: ["izmit"] },
    { id: "bursa-2019", year: 2019, type: "article", title: "Investigating Subsidence in the Bursa Plain, Turkey, Using Ascending and Descending Sentinel-1 Satellite Data", authors: "Gökhan Aslan, Ziyadin Çakır, Cécile Lasserre, François Renard", venue: "Remote Sensing 11(1), 85", url: "https://doi.org/10.3390/rs11010085", citations: 75, themes: ["subsidence"], aois: ["bursa"] },
    { id: "konya-agu-2019", year: 2019, type: "abstract", title: "Rapid subsidence in Konya city (Turkey) revealed by Sentinel-1 InSAR time series", authors: "Nurdan Şireci, Gökhan Aslan, Ziyadin Çakır", venue: "AGU Fall Meeting, G13B-0532", url: "https://ui.adsabs.harvard.edu/abs/2019AGUFM.G13B0532S/abstract", citations: 0, themes: ["subsidence"], aois: ["konya"] },
    { id: "konya-egu-2019", year: 2019, type: "abstract", title: "Investigation of the land subsidence in the Konya plain using hydrogeological and Sentinel-1 time-series data", authors: "Nurdan Şireci, Gökhan Aslan, Ziyadin Çakır", venue: "EGU General Assembly", url: "https://meetingorganizer.copernicus.org/EGU2019/EGU2019-17474.pdf", citations: 0, themes: ["subsidence"], aois: ["konya"] },
    { id: "izmit-egu-2019", year: 2019, type: "abstract", title: "Characterizing interseismic aseismic slip along the 1999 Izmit earthquake rupture (Turkey) from GPS, InSAR and creepmeter measurements", authors: "Gökhan Aslan, Cécile Lasserre, Ziyadin Çakır, Semih Ergintav, Seda Özarpacı, Uğur Doğan, Roger Bilham, François Renard", venue: "EGU General Assembly", url: "https://meetingorganizer.copernicus.org/EGU2019/EGU2019-5788-1.pdf", citations: 0, themes: ["tectonics"], aois: ["izmit"] },
    { id: "istanbul-2018", year: 2018, type: "article", title: "Analysis of Secular Ground Motions in Istanbul from a Long-Term InSAR Time-Series (1992–2017)", authors: "Gökhan Aslan, Ziyadin Çakır, Semih Ergintav, Cécile Lasserre, François Renard", venue: "Remote Sensing 10(3), 408", url: "https://doi.org/10.3390/rs10030408", citations: 63, themes: ["subsidence"], aois: ["istanbul"] },
    { id: "istanbul-egu-2018", year: 2018, type: "abstract", title: "Identification of secular ground motions in Istanbul by long term time-resolved InSAR analysis (1992–2017)", authors: "Gökhan Aslan, Ziyadin Çakır, Semih Ergintav, Cécile Lasserre, François Renard", venue: "EGU General Assembly", url: "https://meetingorganizer.copernicus.org/EGU2018/EGU2018-18018-1.pdf", citations: 1, themes: ["subsidence"], aois: ["istanbul"] },
    { id: "izmit-egu-2018", year: 2018, type: "abstract", title: "Surface creep along the 1999 Izmit earthquake’s rupture (Turkey) from high temporal resolution interferometric synthetic-aperture radar data", authors: "Gökhan Aslan, Ziyadin Çakır, Cécile Lasserre, François Renard, Semih Ergintav", venue: "EGU General Assembly", url: "https://meetingorganizer.copernicus.org/EGU2018/EGU2018-18148-2.pdf", citations: 0, themes: ["tectonics"], aois: ["izmit"] },
    { id: "izmit-agu-2015", year: 2015, type: "abstract", title: "Surface Creep Along the 1999 İzmit Earthquake Rupture (Turkey) from High Temporal Resolution Interferometric Synthetic Aperture Radar Data", authors: "Ziyadin Çakır, Gökhan Aslan, Uğur Doğan, Şinasi Kaya, Semih Ergintav, Deniz Öz, Mehmet F. Çelik", venue: "AGU Fall Meeting, G21A-1007", url: "https://ui.adsabs.harvard.edu/abs/2015AGUFM.G21A1007C/abstract", citations: 0, themes: ["tectonics"], aois: ["izmit"] },
    { id: "masters-thesis-2012", year: 2012, type: "thesis", title: "GPS ölçümleri ve fay hareketlerinde deprem ilişkisi", authors: "Gökhan Aslan", venue: "Master’s thesis · Istanbul Technical University", url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=bg_ePEIAAAAJ&citation_for_view=bg_ePEIAAAAJ:dhFuZR0502QC", citations: 0, themes: ["tectonics"], aois: ["northwest-turkey"] }
  ],
  aois: [
    { id: "french-alps", name: "French Alps", region: "European Alps", lat: 45.2, lng: 6.6 },
    { id: "aral-sea", name: "Aral Sea coast", region: "Central Asia", lat: 44.8, lng: 59.5 },
    { id: "kara-bogaz", name: "Kara-Bogaz-Gol", region: "Turkmenistan", lat: 41.0, lng: 52.9 },
    { id: "gangtok", name: "Gangtok", region: "Sikkim Himalaya", lat: 27.34, lng: 88.61 },
    { id: "north-sikkim", name: "North Sikkim", region: "Sikkim Himalaya", lat: 27.85, lng: 88.55 },
    { id: "joshimath", name: "Joshimath", region: "Uttarakhand, India", lat: 30.56, lng: 79.56 },
    { id: "leo-pargil", name: "Leo Pargil Dome", region: "NW Himalaya", lat: 31.89, lng: 78.63 },
    { id: "santa-cruz", name: "Santa Cruz range", region: "Argentina", lat: -46.6, lng: -72.4 },
    { id: "cape-coral", name: "Cape Coral", region: "Florida, USA", lat: 26.56, lng: -81.95 },
    { id: "istanbul", name: "Istanbul", region: "Türkiye", lat: 41.01, lng: 28.97 },
    { id: "izmit", name: "İzmit rupture", region: "Türkiye", lat: 40.77, lng: 29.92 },
    { id: "bursa", name: "Bursa Plain", region: "Türkiye", lat: 40.2, lng: 29.06 },
    { id: "konya", name: "Konya Plain", region: "Türkiye", lat: 37.87, lng: 32.49 },
    { id: "western-turkey", name: "Western Türkiye geothermal fields", region: "Türkiye", lat: 38.2, lng: 28.2 },
    { id: "northwest-turkey", name: "Northwest Türkiye", region: "Türkiye", lat: 40.55, lng: 29.2 },
    { id: "norway", name: "InSAR Norway", region: "Mainland Norway", lat: 64.5, lng: 12.0 },
    { id: "sorfjorden", name: "Sørfjorden", region: "Norway", lat: 60.2, lng: 6.55 },
    { id: "svalbard", name: "Svalbard", region: "Norwegian Arctic", lat: 78.2, lng: 16.0 },
    { id: "jan-mayen", name: "Jan Mayen", region: "Norwegian Arctic", lat: 71.0, lng: -8.3 }
  ],
  scholarAudit: {
    profileRowsReviewed: 43,
    siteRecords: 35,
    note: "Scholar rows were matched to publisher, repository and conference records. Duplicate language/version records were merged; withdrawn, misattributed and malformed index entries were excluded."
  }
};
